#!/bin/bash

set -e
set -o pipefail

########################################################################
# Load modules
module load python/3.9.9

########################################################################

# Set up running directory
cd "$(dirname "${BASH_SOURCE[0]}")" 

# Create directories to save output files to
mkdir -p ./results/03_cellranger_count_summary

########################################################################
# Run to summarize results generated by CellRanger for all libraries
python ./util/summarize_cellranger_results.py --dir=./results/02_cellranger_count/DefaultParameters \
                                              --outdir=./results/03_cellranger_count_summary/